### PR TITLE
Tag - Final Destination

### PR DESCRIPTION
**Pull request by Bear64DX**
This adds the Final Destination stage from Smash 64 into Tag! This was my first model import of a level I made, and I'm really happy with how it turned out. If there are flaws with the stage, well just to let you know I didn't MAKE MAKE the level, I only imported it. You might notice that the level looks weird on the back side. This is because Smash 64 is a 2D game, and when they made the stage I guess they just didn't bother to make the level appear on the other side of the map. Which is fine because you'd never see it anyway. This however works a bit differently in 3D. Yes, I know there's ripped textures. But I noticed that Bitforts has a lot of ripped textures, yet it seems like that was okay to port. I think it's only fair to add this stage. If you don't that's completely fine but I'm really happy with how it turned out.

### CODE REVIEW

**Comment by EmeraldLoc** [comment]
Does this use ripped textures and what not?

**Comment by Bear64DX** [comment]
I'm not exactly sure. I got the model off of The Models Resource. Ripped textures make it hard to port maps. I'd be really sad if it did. There's no definitive way to check that w/o searching a video of the actual FD map. Quick question, does bitforts actually have ripped textures? I wasn't sure if my map had ripped ones, but when I saw Bitforts' textures I thought it was okay because that also has ripped textures (I think). I'm not sure if the textures are ripped because these ones look like they have higher quality than the actual ones. I can't validate this however, but I hope this is good enough (I wanted to add a custom skybox and music but I don't know how to do that. If we could chat about that sometime that'd be neat)

**Comment by EmeraldLoc** [comment]
*clears throat*

I won't be adding this level anyways due to the simplistic nature of the level.

Now fr, copyright is pretty messy. According to some redditors (extremely reliable), it is a no under all circumstances, if it's under copyright, you can't use it which I definitely agree with. The only time you can really do that is if it is purely a personal project and no one else has access to it. This gets pretty messy, since easily the majority of paintings being used are by Nintendo, so that would be under copyright? idk it's a pretty big mess that I don't understand. Gonna try to stay away from direct rips of levels that contains both textures and level geometry, that feels a lot more direct then say bitforts, which uses the textures in a new way.

Will close this due to copyright (?) and the level being extremely basic.

**Comment by Bear64DX** [comment]
I thought this was kinda gonna happen

**Pull request closed without merging**
