### PR TITLE
Tag - Starry Night Sky

### PR DESCRIPTION
**Pull request by Bear64DX**
This was a map originally made by Blocky for his mod "121st Star". I've gone ahead and decided to port it to Tag.
There is some junk in the levels folder. I kept those files there since I thought they're essential to the level itself.
I'm really happy with this one. I hope you are too. (Oh and you might wanna add Blocky to the map creators credits)

### CODE REVIEW

**Comment by EmeraldLoc** [comment]
If you can remove the actual level data and keep the .lvl file, I'll merge this.

**Comment by Bear64DX** [comment]
You mean those filler PNGs? I can probably do that

**Comment by EmeraldLoc** [comment]
Yea the skybox stuff

**Comment by Bear64DX** [comment]
The SNS files aren't exactly on my PC anymore. I mean they're there but I'm not sure if I'd have to make an entire PR for this or not. At the very least, you could merge the PR and then delete those files. Or merge this and I can make a quick hotfix deleting these files.

**Comment by EmeraldLoc** [comment]
It's ok

**Pull request merged**
